<a href="https://colab.research.google.com/github/2303A51191/B03_PFDS_1191/blob/main/PFDS_LAB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

a = np.array([
    [85, 78, 92],
    [76, 88, 81],
    [90, 94, 89],
    [65, 70, 72],
    [88, 91, 85]
])

print("All Marks:\n", a)


All Marks:
 [[85 78 92]
 [76 88 81]
 [90 94 89]
 [65 70 72]
 [88 91 85]]


In [2]:
b = np.mean(a, axis=1)
c = np.min(a, axis=1)
d = np.max(a, axis=1)

print("\nAverage Marks:", b)
print("Minimum Marks:", c)
print("Maximum Marks:", d)


Average Marks: [85.         81.66666667 91.         69.         88.        ]
Minimum Marks: [78 76 89 65 85]
Maximum Marks: [92 88 94 72 91]


In [3]:
e = a[[0, 2]]
print("\nMarks of Student 1 and 3:\n", e)


Marks of Student 1 and 3:
 [[85 78 92]
 [90 94 89]]


In [4]:
f = np.any(a > 80, axis=1)
g = a[f]

print("\nStudents scoring above 80 in any subject:\n", g)


Students scoring above 80 in any subject:
 [[85 78 92]
 [76 88 81]
 [90 94 89]
 [88 91 85]]


In [5]:
h = a.T
print("\nSubject-wise Marks:\n", h)


Subject-wise Marks:
 [[85 76 90 65 88]
 [78 88 94 70 91]
 [92 81 89 72 85]]


In [6]:
print("\nAnalysis:")
print("• Student 3 has top marks overall.")
print("• Student 4 has lowest average.")
print("• Subject 2 has generally high scores.")
print("• Many students scored above 80 in at least one subject.")


Analysis:
• Student 3 has top marks overall.
• Student 4 has lowest average.
• Subject 2 has generally high scores.
• Many students scored above 80 in at least one subject.
